
```{r}
Sys.setenv(JAVA_HOME = '/Library/Java/JavaVirtualMachines/jdk-11.0.15.1.jdk/Contents/Home')
library(dismo) # interface with MaxEnt
library(raster) # spatial data manipulation
library(MASS) # for 2D kernel density function
library(magrittr) # for piping functionality, i.e., %>%
library(maptools) # reading shapefiles
library(rgeos)
library(rJava)
library(data.table)
```
  

```{r}

locations = data.frame()
record.list <- list.files("pass_occurence_data/", pattern = ".csv", full.names = T)

for (i in 1:7) {
  temp <- fread(record.list[i], select = c("decimalLongitude", "decimalLatitude"))
  locations <- rbind(temp, locations)
}

locations <- fread("passerine_records_1970_onwards.csv", select = c("decimalLongitude", "decimalLatitude"))
```

```{r}
locations <- na.omit(locations)
colnames(locations) <- c("lon", "lat")
climdat <- brick("clim/wc2.1_2.5m_bio_1.tif")
occur.ras <- rasterize(locations, climdat, 1) #b1 here is a climdat file 
plot(occur.ras)
```

```{r}
extent_aus <- c(110, 158, -46, -9)
occur.ras<- crop(occur.ras, extent_aus)
```


```{r}
presences <- which(values(occur.ras) == 1)
pres.locs <- coordinates(occur.ras)[presences, ]

dens <-kde2d(pres.locs[,1], pres.locs[,2],
             n = c(nrow(occur.ras), ncol(occur.ras)))
dens %>%
  raster %>%
  resample(b1, method="bilinear") %>% #b1 here is a raster file of climate data
  crop(extent(b1)) %>%
  writeRaster('biasfile.asc')
biasfile <- raster("biasfile.asc")
mod1 <- maxent(b1, locations, args = "biasfile=biasfile")
```