---
title: "BirdData"
output: html_document
---


```{r}
library(magrittr) # for piping functionality, i.e., %>%
library(maptools) # reading shapefiles
library(rgeos)
library(rJava)
library(data.table)
library(dplyr)
library(sp)
library(spThin) #thinning package

```
Read in variations on preserved data and manipulate by species 

```{r}
#read in data
bird_data <- fread("/Users/u6638201/Desktop/BirdDat/combined_LA_1900_1979/combined_LA_1900_1979.csv", select = c('genus', "specificEpithet", "infraspecificEpithet", "decimalLongitude", "decimalLatitude"))
colnames(bird_data) <- c("genus", "species1", "species2", "longitude", "latitude")
bird_data <- na.omit(bird_data) #omit NA's


# if column 2 has a value, replace column, else, do nothing 
bird_data$species[1] <- paste(bird_data$genus[1], bird_data$species2[1])

for (i in 1:nrow(bird_data)){
if (bird_data$species2[i] == "") {
 bird_data$species[i] <- paste(bird_data$genus[i], bird_data$species1[i])
} else {
   bird_data$species[i] <- paste(bird_data$genus[i], bird_data$species2[i])
}
}

#Subset data
lamberti = subset(bird_data, species == "Malurus lamberti")
assimilis = subset(bird_data, species == "Malurus assimilis")

#thin bird data and write to files
thin(lamberti, "latitude", "longitude", "species", 30, 1, out.dir = "~/Desktop/Maxent/ThinnedBirdData/", out.base = "lamberti_1900_1979_30km")

thin(assimilis, "latitude", "longitude", "species", 30, 1, out.dir = "~/Desktop/Maxent/ThinnedBirdData/", out.base = "assimilis_1900_1979_30km")

#Do same for 1960-1979
bird_data1960 <- fread("/Users/u6638201/Desktop/BirdDat/combined_LA_1960_1979/combined_LA_1960_1979.csv", select = c("decimalLongitude", "decimalLatitude")) %>% mutate(species = "Malurus", .before = "decimalLongitude")
colnames(bird_data1960) <- c("species", "longitude", "latitude")
bird_data1960 <- na.omit(bird_data1960) #omit NA's

#thin and write
thin(bird_data1960, "latitude", "longitude", "species", 30, 1, out.dir = "~/Desktop/Maxent/ThinnedBirdData/", out.base = "combined_1960_1979_30km")

#make for variations on thinning
distance = c(0, 10, 20, 30, 40, 50)
for (i in distance) {
  thin(bird_data, "latitude", "longitude", "genus", i, 1, out.dir = "~/Desktop/Maxent/ThinnedBirdData/", out.base = paste0("combined_1900_1979_", i, "km"))
}

```
Stick maxent results together 1-10
```{r}
#files cannot be read directly from the Maxent/results folder as something about the other files in that directory causes R to produce an error

maxentResults = c()
files <- list.files("~/MaxEnt/RunResults/results", pattern = ".csv", full.names = T)

for (i in files) {
  maxentResults <- rbind(maxentResults, read.csv(i))
}

DatasetDescription <- c("Malurus combined 1900 - 1979 thinned 30km",
                                        "Malurus combined 1900 - 1979 thinned 30km no bias correction", 
                                        "Malurus combined 1960 - 1979 thinned 30km",
                                        "Malurus lamberti 1900 - 1979 thinned 30km",
                                        "Malurus assimilis 1900 - 1979 thinned 30km",
                                        "Malurus combined 1900 - 1979 no thinning",
                                        "Malurus combined 1900 - 1979 thinned 10km",
                                        "Malurus combined 1900 - 1979 thinned 20km",
                                        "Malurus combined 1900 - 1979 thinned 40km",
                                        "Malurus combined 1900 - 1979 thinned 50km")
maxentResults <- cbind(DatasetDescription, maxentResults)
AUC <- data.frame(as.factor(c(1:10)), maxentResults$Test.AUC, maxentResults$Training.AUC)
colnames(AUC) <- c("run", "test", "train")
melted <- melt(AUC)
ggplot(data=melted, aes(x=run, y=value, group = variable)) +
  geom_line(aes(linetype=variable))+
  geom_point() +
  scale_y_continuous(breaks=seq(0,1,0.1), limits = c(0,1))

write.csv(maxentResults,"~/Desktop/Maxent/Results/combined_results.csv")

```



