---
title: "Biasfile_2"
output: html_document
---

This R script creates a biasfile for use with Maxent by creating a raster layer from point data. 

Load required packages
``` {r}
library(tidyverse)
library(raster)
library(sp)
library(rgdal)
library(spatstat)
library(here)
library(tools)
```

Load in environmental layers
```{r}
setwd("~/Honours")
r1 <- raster("data/clim_data/ANUBIOCLIM_ascs/bioclim_01.asc")
```
Create blank raster for template for occurence data
```{r}
blank <- raster(r1)
```
Load in occurrence data
```{r}

locations <- fread("~/Honours/data/bird_data/passerine_records_1970_onwards/passerine_records_1970_onwards.csv", select = c("decimalLongitude", "decimalLatitude"))
colnames(locations) <- c("lon", "lat")
locations <- na.omit(locations)
locations <- SpatialPoints(data.frame(lon = locations$lon, lat = locations$lat))
crs(locations) <- CRS('+init=EPSG:4326')

record.list <- list.files("pass_occurence_data/", pattern = ".csv", full.names = T)
locations = data.frame()

for (i in 1:7) {
  temp <- fread(record.list[i], select = c("decimalLongitude", "decimalLatitude"))
  locations <- rbind(temp, locations)
}
colnames(locations) <- c("lon", "lat")
locations <- na.omit(locations)
locations <- SpatialPoints(data.frame(lon = locations$lon, lat = locations$lat))
crs(locations) <- CRS('+init=EPSG:4326')

```

Count occurences
```{r}
# Get count of occurrence points in each cell
oc.ras.bin <- rasterize(locations, blank, fun = 'count', na.rm = F)
# All cells with count >= 1 get assigned a 1 value
oc.ras.bin[oc.ras.bin >= 1] <- 1
# Redundancy to enforce consistent NA values
oc.ras.bin[is.na(oc.ras.bin)] <- 0.00001
# Mask away any water/missing data
oc.ras.bin <- mask(oc.ras.bin, r1)
# Match bias NA values with env. layers
NAvalue(oc.ras.bin) <- NAvalue(r1)
compareRaster(oc.ras.bin, r1)
```

Make a spatial mask 
```{r}
poly_expand <- function(ocr, exp_factor){
return(Polygon(rbind(c(matrix(bbox(ocr), 2, 2)[1,1] - exp_factor,
matrix(bbox(ocr), 2, 2)[2,2] + exp_factor),
c(matrix(bbox(ocr), 2, 2)[1,1] - exp_factor,
matrix(bbox(ocr), 2, 2)[2,1] - exp_factor),
c(matrix(bbox(ocr), 2, 2)[1,2] + exp_factor,
matrix(bbox(ocr), 2, 2)[2,1] - exp_factor),
c(matrix(bbox(ocr), 2, 2)[1,2] + exp_factor,
matrix(bbox(ocr), 2, 2)[2,2] + exp_factor),
c(matrix(bbox(ocr), 2, 2)[1,1] - exp_factor,
matrix(bbox(ocr), 2, 2)[2,2] + exp_factor)))
)
}
p <- poly_expand(ocr = locations, exp_factor = 1)
px <- Polygons(list(p), 1)
spat.mask <- SpatialPolygons(list(px),
proj4string = CRS('+init=EPSG:4326 +proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0'))
```

Applying spatial mask 
```{r}
# Extract new rasters by spatial mask
r1_mod <- crop(r1, spat.mask)
bias.bin <- crop(oc.ras.bin, spat.mask)
# Double-check alignment between environmental layers and bias raster
compareRaster(r1_mod, bias.bin)
# Write new environemntal raster information with modified names
writeRaster(r1_mod, 'r1_modified.asc', overwrite = T)
# Export bias layer
writeRaster(bias.bin, 'bias_mask_bin_modified.asc', overwrite = T)

```

