---
title: "LandCoverPCA"
output: html_document
---


```{r}
library(ncdf4)
library(terra) # package for spatraster manipulation
library(raster) # package for raster manipulation
library(rgdal) # package for geospatial analysis
library(ggplot2) # package for plotting
library(maptools)
library(magrittr) #piping
library(devtools)
library(ggbiplot) #PCA visualisation
library(factoextra) #PCA

#Setup environment
setwd("~/Desktop/LandCover")
ld_states <- nc_open("LUH2_GCB2019_states.nc4")

#Set extents
lon <- ncvar_get(ld_states, "lon")
lon[lon > 180] <- lon[lon > 180] - 360
lat <- ncvar_get(ld_states, "lat", verbose = F)
t <- ncvar_get(ld_states, "time")

```

```{r}
#Make arrays of variables to make data extraction easier 
arraylist <- list()
varlist <- c("pastr", "primf", "primn", "range", "secdf", "secdn", "secma", "secmb", "urban")
extent_aus <- c(110, 158, -46, -9)

AddArray <- function(var){
  var.array <- ncvar_get(ld_states, var)
  fillvalue <- ncatt_get(ld_states, var, "_FillValue")
  var.array[var.array == fillvalue$value] <- NA
  return(var.array)
}

#add them to a list
for(i in varlist) {
    variable <- AddArray(i)  ## define which variable to be added
    arraylist[[paste0(i,".array")]] <- variable
  }


#Function to sample a selected year and variable
SampleRaster <- function(vararray, year) {
year1 <- year - 849
var.slice <- vararray[year1, ,]
ras <- raster(t(var.slice), xmn=min(lon), xmx=max(lon), ymn=min(lat), ymx=max(lat), crs=CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs+ towgs84=0,0,0"))
ras <- flip(ras, direction='y')
ran <- sampleRandom(ras, 1000, na.rm = T, extent_aus, F, F, T, T, F)
write.csv(ran, paste0("~/Desktop/LandCover/PCAfiles/", vararray, year, ".csv"))
}


#loop to extract data for each year
yearlist <- c(1980:2018)
for (i in arraylist) {
  lapply(yearlist, SampleRaster, var.array = i)
 }

#read list of .csv files containing data
setwd("~/Desktop/LandCover/PCAfiles/")
temp = list.files(pattern="*.csv")
 for (i in 1:length(temp)) assign(temp[i], read.csv(temp[i]))

#extract column of layer values
d1 <- RandomSamplepastr.csv[[4]]
d2 <- RandomSampleprimf.csv[[4]]
d3 <- RandomSampleprimn.csv[[4]]
d4 <- RandomSamplerange.csv[[4]]
d5 <- RandomSamplesecdf.csv[[4]]
d6 <- RandomSamplesecdn.csv[[4]]
d7 <- RandomSamplesecma.csv[[4]]
d8 <- RandomSamplesecmb.csv[[4]]
d9 <- RandomSampleurban.csv[[4]]

PCAData <- data.frame(d1, d2, d3, d4, d5, d6, d7, d8, d9)
colnames(PCAData) <- c( "pastr", "primf", "primn", "range", "secdf", "secdn","secma", "secmb", "urban")
write.csv(PCAData, "PCAData.csv")

## ACTUAL PCA PART
landcover.pca <- prcomp(PCAData, scale = TRUE)
fviz_eig(landcover.pca)
fviz_pca_ind(landcover.pca,
             col.ind = "cos2", # Color by the quality of representation
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE     # Avoid text overlapping
)
# Eigenvalues
eig.val <- get_eigenvalue(landcover.pca)
eig.val

# Results for Variables
landcover.pca <- get_pca_var(landcover.pca)
landcover.pca$coord          # Coordinates
landcover.pca$contrib        # Contributions to the PCs
landcover.pca$cos2           # Quality of representation 
# Results for individuals
landcover.ind <- get_pca_ind(landcover.pca)
landcover.ind$coord          # Coordinates
landcover.ind$contrib        # Contributions to the PCs
landcover.ind$cos2           # Quality of representation 

fviz_pca_var(landcover.pca,
             col.var = "contrib", # Color by contributions to the PC
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE     # Avoid text overlapping
)


```

Visualise PCA
```{r} 
ggbiplot(landcover.pca, obs.scale = 1, var.scale = 1,
         ellipse = TRUE, circle = TRUE) +
  scale_color_discrete(name = '') +
  theme(legend.direction = 'horizontal', legend.position = 'top')
```